cli_decoding:
  adblock: false
  aggressive: false
  rpz: false
  wildcard: false
cli_testing:
  autocontinue: true
  chancy_tester: false
  cidr_expand: false
  complements: false
  cooldown_time: 0.0
  days_between:
    db_clean: 28
    db_retest: 7
  db_type: csv
  display_mode:
    all: true
    colour: true
    dots: false
    execution_time: true
    less: true
    max_registrar: 0
    percentage: true
    quiet: false
    registrar: false
    simple: false
    status: all
  file_filter: null
  file_generation:
    analytic: true
    hosts: false
    merge_output_dirs: false
    no_file: false
    plain: true
    unified_results: false
  hosts_ip: 0.0.0.0
  inactive_db: true
  local_network: false
  max_workers: null
  mining: false
  sorting_mode:
    hierarchical: true
    standard: true
  testing_mode:
    availability: true
    platform_contribution: false
    reputation: false
    syntax: false
  whois_db: false
collection:
  preferred_status_origin: recommended
  push: true
debug:
  active: false
  level: info
dns:
  delay: 0.0
  follow_server_order: true
  protocol: UDP
  server:
    - 9.9.9.10
    - 149.112.112.10
  trust_server: true
http_codes:
  list:
    potentially_down:
      - 400
      - 402
      - 404
      - 409
      - 410
      - 412
      - 414
      - 415
      - 416
      - 451
    potentially_up:
      - 300
      - 301
      - 302
      - 303
      - 304
      - 305
      - 307
      - 308
      - 403
      - 405
      - 406
      - 407
      - 408
      - 411
      - 413
      - 417
      - 418
      - 421
      - 422
      - 423
      - 424
      - 426
      - 428
      - 431
      - 500
      - 501
      - 502
      - 503
      - 504
      - 505
      - 506
      - 507
      - 508
      - 510
      - 511
    up:
      - 100
      - 101
      - 102
      - 200
      - 201
      - 202
      - 203
      - 204
      - 205
      - 206
      - 207
      - 208
      - 226
      - 429
  self_managed: false
lookup:
  collection: true
  dns: true
  http_status_code: true
  netinfo: true
  reputation: false
  special: true
  timeout: 5
  whois: true
max_http_retries: 3
share_logs: false
user_agent:
  browser: firefox
  custom: null
  platform: linux
verify_ssl_certificate: true
